//This file loads all the words into the arrays and makes them Uppercased
const temp1 = [
    "THE FOUR MUSKETEERS-ATHOS", "THE FOUR MUSKETEERS-D'ARTAGNAN", "THE FOUR MUSKETEERS-PORTHOS", "THE FOUR MUSKETEERS-ARAMIS",
    "ALTER EGOS OF SUPERHEROES-BRUCE WAYNE", "ALTER EGOS OF SUPERHEROES-CLARK KENT", "ALTER EGOS OF SUPERHEROES-PETER PARKER", "ALTER EGOS OF SUPERHEROES-DIANA PRINCE",
    "MONOPOLY STREETS-VINE", "MONOPOLY STREETS-FLEET", "MONOPOLY STREETS-REGENT", "MONOPOLY STREETS-OXFORD",
    "PLACES ONCE HAVING THE HIGHEST CONSTRUCTION-LINCOLN", "PLACES ONCE HAVING THE HIGHEST CONSTRUCTION-ROUEN", "PLACES ONCE HAVING THE HIGHEST CONSTRUCTION-WASHINGTON", "PLACES ONCE HAVING THE HIGHEST CONSTRUCTION-EGYPT"];

let longCat = ["THE FOUR MUSKETEERS", "ALTER EGOS OF SUPERHEROES", "MONOPOLY STREETS", "PLACES ONCE HAVING THE HIGHEST CONSTRUCTION"]
const catsWords = temp1.map(function (e) {
    return e.toUpperCase()
});

longCat = longCat.map(function (e) {
    return e.toUpperCase()
});
let shortCat = [];

shortCat[0] = catsWords[0].split('-')[0];
shortCat[1] = catsWords[4].split('-')[0];
shortCat[2] = catsWords[8].split('-')[0];
shortCat[3] = catsWords[12].split('-')[0];