//This file loads all the words into the arrays and makes them Uppercased
const temp1 = [
    "COUNTRIES ON THE EQUATOR-ECUADOR", "COUNTRIES ON THE EQUATOR-BRAZIL", "COUNTRIES ON THE EQUATOR-KENYA", "COUNTRIES ON THE EQUATOR-INDONESIA",
    "COUNTRIES ON THE NORTHERN HEMISPHERE-SYRIA", "COUNTRIES ON THE NORTHERN HEMISPHERE-SPAIN", "COUNTRIES ON THE NORTHERN HEMISPHERE-CANADA", "COUNTRIES ON THE NORTHERN HEMISPHERE-FINLAND",
    "COUNTRIES ON THE SOUTHERN  HEMISPHERE-GABON", "COUNTRIES ON THE SOUTHERN  HEMISPHERE-UGANDA", "COUNTRIES ON THE SOUTHERN  HEMISPHERE-COLUMBIA", "COUNTRIES ON THE SOUTHERN  HEMISPHERE-KIRIBATI",
    "COUNTRIES THAT PLAY IN THE 6 NATIONS-ITALY", "COUNTRIES THAT PLAY IN THE 6 NATIONS-SCOTLAND", "COUNTRIES THAT PLAY IN THE 6 NATIONS-FRANCE", "COUNTRIES THAT PLAY IN THE 6 NATIONS-IRELAND"];

let longCat = ["COUNTRIES ON THE EQUATOR", "COUNTRIES ON THE NORTHERN HEMISPHERE", "COUNTRIES ON THE SOUTHERN  HEMISPHERE", "COUNTRIES THAT PLAY IN THE 6 NATIONS"]
const catsWords = temp1.map(function (e) {
    return e.toUpperCase()
});

longCat = longCat.map(function (e) {
    return e.toUpperCase()
});
let shortCat = [];

shortCat[0] = catsWords[0].split('-')[0];
shortCat[1] = catsWords[4].split('-')[0];
shortCat[2] = catsWords[8].split('-')[0];
shortCat[3] = catsWords[12].split('-')[0];